import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { pinoHttp } from 'pino-http';
import { env } from './config/env.js';
import { errorHandler, notFound } from './lib/errors.js';
import { logger } from './lib/logger.js';
import { gstRouter } from './routes/gst.routes.js';
import { invoiceRouter } from './routes/invoice.routes.js';
import { upiRouter } from './routes/upi.routes.js';

export const app = express();
app.disable('x-powered-by');
app.use(pinoHttp({ logger, redact: ['req.headers.authorization', 'req.headers.x-cron-secret'] }));
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: env.FRONTEND_ORIGIN, methods: ['GET', 'POST'], credentials: false, maxAge: 86_400 }));
app.use(express.json({ limit: '256kb', type: 'application/json' }));
app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: 'draft-7', legacyHeaders: false }));
app.get('/health', (_req, res) => res.json({ ok: true }));
app.use('/api/invoices', invoiceRouter);
app.use('/api/gst', gstRouter);
app.use('/api/upi', upiRouter);
app.use(notFound);
app.use(errorHandler);
